### ISSUE TITLE
Why MITRE CEE ? Why not Cybox ?

### ISSUE THREAD

**Issue by GenEars** [sepses/slogert#14]
Dear SLOGERT team,
I'm wondering why you are using MITREE CEE for log annotations as the CEE project has been stopped since 2014 ...

My guess is that 1) CEE is more "log oriented" than Cybox so it may look intuitively closer to the data managed by SLOGERT, 2) you started SLOGERT with CEE in mind and Cybox came after but you didn't had time to move to Cybox, 3) CEE's objects and event taxonomy tagging is easier to implement and use.

... you may however have other reasons non obvious to mee.
I hope that you won't find my question awkward and that you'll share your insights with me.

Best regards,
LTa.

**Comment by andrenios** [comment]
Dear LTa,

thank you, it is a good question.
The main goal of SLOGERT is the construction of knowledge graphs from arbitrary raw log messages, hence, we were looking for ontologies and taxonomies to represent information from log events.
[CEE ](https://cee.mitre.org/language/1.0-beta1/core-profile.html) is one of the initiatives that offers a detailed taxonomy on general log events, and despite being discontinued, this taxonomy is still the most extensive and best fitting for our idea.

CybOX has been integrated into STIX 2.0 as STIX Cyber Observables. It is focused on the exchange of cyber threat intelligence information, not directly on log representation in general.
For the ontology creation we also considered those vocabularies, and it should be straightforward to map some of the concepts/terms from the STIX vocabulary, in particular for indicator representation, such as url, domain-name, ipv4-addr, filename, etc.

We also worked on Knowledge Graphs specific for the Cybersecurity Domain, maybe this is also interesting for you
[The SEPSES Knowledge Graph: An Integrated Resource for Cybersecurity](https://link.springer.com/chapter/10.1007/978-3-030-30796-7_13) (ISWC 2019)

I hope this explains our idea behind the choice.
Please do not hesitate to contact us if you have further questions or feedback.

**Comment by GenEars** [comment]
Thanks for the detailed answer. Useful insights.
