### ISSUE TITLE
Maybe the files in the directory of "output/auth.log/3-ottr" are mistakenly named.

### ISSUE THREAD

**Issue by SycIsDD** [sepses/slogert#15]
Congratulations on a very useful piece of work you have done, which has given us a lot of inspiration, in the paper named "The SLOGERT Framework for Automated Log Knowledge Graph Construction". However, we have found that the stOTTR format is used to store the instance files and the OTTR format is used to store the templates. But in this directory, the suffix of filename does not match the description in the paper. So I think maybe the files in this directory are mistakenly named. If not, then my understanding of the paper is wrong. 
Looking forward to your reply and correction. @fekaputra

**Comment by SycIsDD** [comment]
@fekaputra

**Comment by fekaputra** [comment]
Hi @SycIsDD, thanks for both your interest and your feedback! yes, this is an error on our side, I'll update both the file naming mechanism and the example that we provided in the repository. thanks again!

**Comment by fekaputra** [comment]
Addressed in commit https://github.com/sepses/slogert/commit/21faed2cb088e8c3cc553fdb68f3a4118ca4b1c5
