### ISSUE TITLE
Problem with running the tests

### ISSUE THREAD

**Issue by Franklin110120** [sepses/slogert#20]
Hi there,

After I git clone the repository and run "mvn clean install", I encountered an FileNotFound error as below:
<img width="684" alt="image" src="https://user-images.githubusercontent.com/43932842/181376489-0e1809d1-99ce-4123-a898-e33365dbec4a.png">

It would seem that the csv files cannot be generated. The whole "2-logpai" and "4-ttl" folders are missing. Any idea what may have caused this issue?
My environment should be able to meet the software's prerequisites:
<img width="874" alt="image" src="https://user-images.githubusercontent.com/43932842/181377169-30316982-5998-4360-af50-6fce208e51d8.png">
I have java 11, apache maven, and python2.7 with pandas and scipy installed.

**Comment by Franklin110120** [comment]
I have pinpointed the error in scenario.py. It would seem to be a library import error for that python file that generates the "2-logpai" folder.

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/43932842/181656393-9177b70e-46ea-4b49-9747-2796c8e4f8f8.png">

from scipy.linalg import _fblas reports an error.

**Comment by hashim-ch** [comment]
@Franklin110120 how did you fix it?
